## Numpy array and basics
Learn about numpy

In [4]:
import numpy as np

## Creating array from list

In [3]:
arr_1d = np.array([1, 2, 3, 4, 5])
print("1D array: ", arr_1d)

arr_2d = np.array([[1,2,3], [4,5,6]])
print("2D array: ", arr_2d)

1D array:  [1 2 3 4 5]
2D array:  [[1 2 3]
 [4 5 6]]


### Numpy array vs List

In [ ]:
py_list = [1, 2, 3]
print("List multiplication", py_list * 2)

np_array = np.array([1, 2, 3]) #element wise multiplication
print("Array multiplication", np_array * 2)


List multiplication [1, 2, 3, 1, 2, 3]
Array multiplication [2 4 6]


## Numpy array vs List operation time

In [7]:
import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time ", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time ", time.time() - start)


 List operation time  0.062159061431884766

 Numpy operation time  0.0072362422943115234


## Creating array from scratch

In [15]:
#Creating zeros array
zeros = np.zeros((3,4))
print("Zeros array: \n", zeros)


# Creating ones array
ones = np.ones((3, 4))
print("Ones array: \n", ones)


#Creating constant number array
full = np.full((3,4), 5)
print("Constant array: \n", full)


#Creating random array (0 to 1)
random = np.random.random((3, 4))
print("Random array: \n", random)


#creating sequence array
seq = np.arange(0, 11, 2)
print("Sequence array: \n", seq)


Zeros array: 
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Ones array: 
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
Constant array: 
 [[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]
Random array: 
 [[0.37025408 0.23809082 0.35100594 0.24383022]
 [0.59911696 0.14156952 0.16590867 0.13259109]
 [0.31193681 0.42018184 0.0089475  0.62027311]]
Sequence array: 
 [ 0  2  4  6  8 10]


## Vector, Matrix, and Tensor

In [18]:
#Creating vector
vector = np.array([1, 2, 3, 4])
print("Vector: ", vector)


#Creating matrix
matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix: ", matrix)

#Creating tensor
tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor: ", tensor)

Vector:  [1 2 3 4]
Matrix:  [[1 2 3]
 [4 5 6]]
Tensor:  [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


## Array Properties

In [19]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape: ", arr.shape)
print("Dimension: ", arr.ndim)
print("Size: ", arr.size)
print("Data Type: ", arr.dtype)

Shape:  (2, 3)
Dimension:  2
Size:  6
Data Type:  int64


## Array Reshaping

In [ ]:
#Reshape an array
arr = np.arange(12)
print("Original array: ", arr)

reshaped = arr.reshape((3, 4))
print("\n Reshaped array: ", reshaped)

#Flattened array
flattened = reshaped.flatten()
print("\n Flattern array: ", flattened)

#Ravel array (returns view, instead of copy)
ravel = reshaped.ravel()
print("\n Ravel array: ", ravel)

#Tranpose array
transpose = reshaped.T
print("\n Transpose array: ", transpose)

Original array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Reshaped array:  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]

 Flattern array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Ravel array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]

 Transpose array:  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
