## Array Operations

In [1]:
import numpy as np

In [ ]:
# 1-D array
arr = np.arange(12)
print("Array: ", arr)
print("Basic Slicing: ", arr[2:8])
print("With Step: ", arr[1: 8: 2])
print("Negative indexing: ", arr[-3])

Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Basic Slicing:  [2 3 4 5 6 7]
With Step:  [1 3 5 7]
Negative indexing:  9


In [8]:
# 2-D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Specific element: ", arr_2d[2, 1])
print("Entire Row: ", arr_2d[1])
print("Entire Column: ", arr_2d[:, 2])

Specific element:  8
Entire Row:  [4 5 6]
Entire Column:  [3 6 9]


## Sorting

In [15]:
# 1-D array sorting
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array: ", np.sort(unsorted))

# 2-D array sorting
arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column: ", np.sort(arr_2d_unsorted, axis=0))

Sorted Array:  [1 1 2 3 4 5 6 9]
Sorted 2D array by column:  [[1 1]
 [2 2]
 [3 3]]


## Filtering

In [17]:
numbers = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
even_number = numbers[numbers % 2 == 0]
print("Even numbers: ", even_number)

odd_number = numbers[numbers % 2 != 0]
print("Odd numbers: ", odd_number)

Even numbers:  [ 2  4  6  8 10]
Odd numbers:  [1 3 5 7 9]


## Filter with mask

In [20]:
mask = numbers > 5
print("Numbers greater than 5: ", mask) # return boolean value
print("Numbers greater than 5: ", numbers[mask]) # return elements

Numbers greater than 5:  [False False False False False  True  True  True  True  True]
Numbers greater than 5:  [ 6  7  8  9 10]


## np.where()

In [ ]:
indices = [3, 5, 7, 9]
print(numbers[indices]) #return index values

where_result = np.where(numbers > 3)
print("Where result: ", where_result) # return indices
print("NP where: ", numbers[where_result]) # return elements

[ 4  6  8 10]
Where result:  (array([3, 4, 5, 6, 7, 8, 9]),)
NP where:  [ 4  5  6  7  8  9 10]


## Adding and Removing from array

In [41]:
# Concatenate two array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

concat = np.concatenate((arr1, arr2))
print("Concatenate two arrays: ", concat)

# Sum of two array
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

sum = (arr1 + arr2)
print("Concatenate two arrays: ", sum)


# Check array shape
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print("Shape of two arrays: ", a.shape == b.shape)


# Add new row into array
original_array = np.array([[1, 2], [3, 4], [5, 6]])
new_array = np.array([[7, 8]])

add_new_row = np.vstack((original_array, new_array))
print("Original array: ", original_array)
print("Adding new row: ", add_new_row)

# Add new column
new_col = np.array([[9], [10], [11]])

add_new_col = np.hstack((original_array, new_col))
print("Original array: ", original_array)
print("Adding new col: ", add_new_col)


# Delete from 2-D array
arr = np.array([[1, 2, 3], [4, 5, 6,], [7, 8, 9]])
deleted = np.delete(arr, 1, 0)
print("Delete from 2D array: ", deleted)

# Delete from 1-D array
arr = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]])
deleted = np.delete(arr, 4)
print("Delete from 1D array: ", deleted)


Concatenate two arrays:  [1 2 3 4 5 6]
Concatenate two arrays:  [5 7 9]
Shape of two arrays:  True
Original array:  [[1 2]
 [3 4]
 [5 6]]
Adding new row:  [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Original array:  [[1 2]
 [3 4]
 [5 6]]
Adding new col:  [[ 1  2  9]
 [ 3  4 10]
 [ 5  6 11]]
Delete from 2D array:  [[1 2 3]
 [7 8 9]]
Delete from 1D array:  [1 2 3 4 6 7 8 9]
